services:
  - type: web
    name: threadly-flask-api
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python Threadly_SDK/app.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false  # You will set this manually in the Render dashboard
    autoDeploy: true
